#pragma once

#define SUCCESS 0
#define CLIENT_DISCONNCTED 1
#define INCORRECT_UN_OR_PW 2
#define ALREADY_REGISTERED 3
#define REGISTRATION_FAILED 4
#define FAILED_TO_SEND 5
#define CHAR_LIMIT_REACHED 6
#define LOG_RETRIEVAL_FAILED 7
#define INCORRECT_COMMAND 8
#define INCORRECT_PORT 9
#define CAPACITY_REACHED 10
#define INCORRECT_IP 11
#define NOT_LOGGED_IN 12
#define INTERNAL_ERROR 13

